name: islamic_kit
description: "Comprehensive Islamic toolkit for Flutter: prayer times, Qibla compass, Hijri calendar, Zakat calculator & Islamic events widgets."
# Package links
homepage: https://github.com/hashimhameem/islamic_kit
repository: https://github.com/hashimhameem/islamic_kit
issue_tracker: https://github.com/hashimhameem/islamic_kit/issues
# Pub.dev search topics
topics:
  - islamic
  - qibla
  - prayer-times
  - hijri
  - zakat
version: 0.1.0

environment:
  sdk: ^3.8.0
  flutter: ">=3.16.0"

dependencies:
  adhan: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_local_notifications: ^17.0.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  hijri: ^3.0.0
  intl: ^0.19.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
